<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMS.Core\DMS.Core.csproj" />
    <ProjectReference Include="..\DMS.Shared\DMS.Shared.csproj" />
  </ItemGroup>

</Project>
