<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\dms_systemicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\DMS_SystemIcon.ico" />
    <None Remove="Assets\LogoHG.jpg" />
    <None Remove="Config\transactions.json" />
    <None Remove="Config\users.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\DMS_SystemIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\LogoHG.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\transactions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\users.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMS.Core\DMS.Core.csproj" />
    <ProjectReference Include="..\DMS.Data\DMS.Data.csproj" />
    <ProjectReference Include="..\DMS.Integration.Mes\DMS.Integration.Mes.csproj" />
    <ProjectReference Include="..\DMS.Integration.Sap\DMS.Integration.Sap.csproj" />
    <ProjectReference Include="..\DMS.Shared\DMS.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Services\DmsWindowChromeStyler.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
  </ItemGroup>

</Project>
