<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DMS.Core\DMS.Core.csproj" />
    <ProjectReference Include="..\..\src\DMS.Shared\DMS.Shared.csproj" />
  </ItemGroup>

</Project>
