using System.IO;
using System.IO.Compression;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using DMS.Desktop.Services.Framework;
using Microsoft.Win32;

namespace DMS.Desktop.Views.Framework;

public partial class FrameworkReleaseHealthView : UserControl
{
    private readonly Func<DmsReleaseHealthReport> _runHealthCheck;
    private readonly string _logsRoot;
    private readonly Func<string,string> _translate;
    private readonly Action<string> _executeTransaction;
    private readonly Action<string,string> _log;
    private DmsReleaseHealthReport? _report;

    public FrameworkReleaseHealthView(Func<DmsReleaseHealthReport> runHealthCheck,string logsRoot,Func<string,string> translate,Action<string> executeTransaction,Action<string,string> log)
    { InitializeComponent(); _runHealthCheck=runHealthCheck; _logsRoot=logsRoot; _translate=translate; _executeTransaction=executeTransaction; _log=log; ApplyLocalization(); SeverityFilter.ItemsSource=new[]{T("Framework.FW11.Filter.All","All results"),T("Framework.FW11.Filter.Blockers","Blockers"),"WARNING","OK","INFO"}; SeverityFilter.SelectedIndex=0; OpenRelatedButton.IsEnabled=false; Loaded+=(_,_)=>RunCalibration(); }
    private string T(string key,string fallback){var value=_translate(key);return string.IsNullOrWhiteSpace(value)||value.StartsWith("[[",StringComparison.Ordinal)?fallback:value;}
    private void ApplyLocalization()
    {
        TitleText.Text=T("Framework.FW11.Title","FW11 — Release health"); SubtitleText.Text=T("Framework.FW11.Description","Final production calibration across configuration, localization, UI, logging, security, workflow, performance and master data.");
        RunButton.Content=T("Framework.FW11.Run","Run calibration"); OpenRelatedButton.Content=T("Framework.FW11.OpenRelated","Open related tool"); CopyButton.Content=T("Framework.FW11.Copy","Copy report"); ExportHtmlButton.Content=T("Framework.FW11.ExportHtml","Export HTML"); ExportJsonButton.Content=T("Framework.FW11.ExportJson","Export JSON"); SupportZipButton.Content=T("Framework.FW11.SupportZip","Support ZIP"); LogButton.Content=T("Framework.FW11.OpenLog","Open LOG03");
        VerdictLabel.Text=T("Framework.FW11.Verdict","Release health"); RqiLabel.Text=T("Framework.FW11.Rqi","Release Quality Index"); FilterLabel.Text=T("Framework.FW11.Filter","Result filter"); CriticalLabel.Text=T("Framework.FW11.Critical","Critical"); ErrorsLabel.Text=T("Framework.FW11.Errors","Errors"); WarningsLabel.Text=T("Framework.FW11.Warnings","Warnings"); PassedLabel.Text=T("Framework.FW11.Passed","Passed"); InfoLabel.Text=T("Framework.FW11.Info","Info");
        SeverityColumn.Header=T("Framework.FW11.Column.Severity","Severity"); FrameworkColumn.Header=T("Framework.FW11.Column.Framework","Framework"); CategoryColumn.Header=T("Framework.FW11.Column.Category","Category"); CheckColumn.Header=T("Framework.FW11.Column.Check","Check"); DetailsColumn.Header=T("Framework.FW11.Column.Details","Details"); SourceColumn.Header=T("Framework.FW11.Column.Source","Source"); FixColumn.Header=T("Framework.FW11.Column.Fix","Open");
        FooterText.Text=T("Framework.FW11.Footer","FW11 never auto-repairs business data. Resolve blockers in the owning administration transaction. The publish script also runs a headless release gate by default.");
    }
    private void RunButton_Click(object sender,RoutedEventArgs e)=>RunCalibration(); private void SeverityFilter_SelectionChanged(object sender,SelectionChangedEventArgs e)=>ApplyFilter();
    private void ResultsGrid_SelectionChanged(object sender,SelectionChangedEventArgs e)=>OpenRelatedButton.IsEnabled=ResultsGrid.SelectedItem is DmsReleaseCheckResult row&&!string.IsNullOrWhiteSpace(row.FixTransaction);
    private void ResultsGrid_MouseDoubleClick(object sender,MouseButtonEventArgs e)=>OpenRelated(); private void OpenRelatedButton_Click(object sender,RoutedEventArgs e)=>OpenRelated(); private void LogButton_Click(object sender,RoutedEventArgs e)=>_executeTransaction("LOG03");
    private void RunCalibration(){Cursor=Cursors.Wait;try{_report=_runHealthCheck();VerdictValue.Text=_report.Verdict;RqiValue.Text=$"{_report.ReleaseQualityIndex:0.0} / 100";VersionValue.Text=$"v{_report.Version} | {_report.Environment}";CriticalValue.Text=_report.CriticalCount.ToString();ErrorsValue.Text=_report.ErrorCount.ToString();WarningsValue.Text=_report.WarningCount.ToString();PassedValue.Text=_report.OkCount.ToString();InfoValue.Text=_report.InfoCount.ToString();GateValue.Text=_report.BuildAllowed?T("Framework.FW11.BuildAllowed","✓ Build gate: ALLOWED"):T("Framework.FW11.BuildBlocked","✕ Build gate: BLOCKED");GeneratedValue.Text=string.Format(T("Framework.FW11.Generated","Generated {0}; {1} checks."),_report.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss"),_report.Results.Count);ApplyBrush();ApplyFilter();_log("RELEASE_HEALTH",$"Verdict={_report.Verdict}; RQI={_report.ReleaseQualityIndex:0.0}; Critical={_report.CriticalCount}; Errors={_report.ErrorCount}; Warnings={_report.WarningCount}; BuildAllowed={_report.BuildAllowed}");}finally{Cursor=null;}}
    private void ApplyFilter(){if(_report is null||SeverityFilter.SelectedItem is not string selected){ResultsGrid.ItemsSource=null;return;}IEnumerable<DmsReleaseCheckResult> rows=_report.Results;var all=T("Framework.FW11.Filter.All","All results");var blockers=T("Framework.FW11.Filter.Blockers","Blockers");if(string.Equals(selected,blockers,StringComparison.OrdinalIgnoreCase))rows=rows.Where(x=>x.IsBlocking);else if(!string.Equals(selected,all,StringComparison.OrdinalIgnoreCase))rows=rows.Where(x=>string.Equals(x.Severity,selected,StringComparison.OrdinalIgnoreCase));ResultsGrid.ItemsSource=rows.ToList();}
    private void ApplyBrush(){if(_report is null)return;var key=!_report.BuildAllowed?"DmsErrorBrush":_report.WarningCount>0?"DmsWarningBrush":"DmsAccentBrush";if(Application.Current.TryFindResource(key) is Brush brush){VerdictValue.Foreground=brush;GateValue.Foreground=brush;RqiValue.Foreground=brush;}}
    private void OpenRelated(){if(ResultsGrid.SelectedItem is DmsReleaseCheckResult row&&!string.IsNullOrWhiteSpace(row.FixTransaction))_executeTransaction(row.FixTransaction);}
    private void CopyButton_Click(object sender,RoutedEventArgs e){if(_report is null)return;Clipboard.SetText(Plain(_report));_log("RELEASE_REPORT_COPY",$"Verdict={_report.Verdict}; Rows={_report.Results.Count}");}
    private void ExportHtmlButton_Click(object sender,RoutedEventArgs e){if(_report is null)return;var d=new SaveFileDialog{Title=T("Framework.FW11.ExportHtml","Export HTML"),Filter="HTML (*.html)|*.html|All files (*.*)|*.*",FileName=$"dms-release-health-{DateTime.Now:yyyyMMdd-HHmmss}.html"};if(d.ShowDialog()!=true)return;File.WriteAllText(d.FileName,Html(_report),Encoding.UTF8);GeneratedValue.Text=string.Format(T("Framework.FW11.Exported","Exported: {0}"),d.FileName);}
    private void ExportJsonButton_Click(object sender,RoutedEventArgs e){if(_report is null)return;var d=new SaveFileDialog{Title=T("Framework.FW11.ExportJson","Export JSON"),Filter="JSON (*.json)|*.json|All files (*.*)|*.*",FileName=$"dms-release-health-{DateTime.Now:yyyyMMdd-HHmmss}.json"};if(d.ShowDialog()!=true)return;File.WriteAllText(d.FileName,Json(_report),Encoding.UTF8);GeneratedValue.Text=string.Format(T("Framework.FW11.Exported","Exported: {0}"),d.FileName);}
    private void SupportZipButton_Click(object sender,RoutedEventArgs e){if(_report is null)return;var d=new SaveFileDialog{Title=T("Framework.FW11.SupportZip","Support ZIP"),Filter="ZIP (*.zip)|*.zip|All files (*.*)|*.*",FileName=$"dms-release-support-{DateTime.Now:yyyyMMdd-HHmmss}.zip"};if(d.ShowDialog()!=true)return;CreateZip(d.FileName,_report);GeneratedValue.Text=string.Format(T("Framework.FW11.Exported","Exported: {0}"),d.FileName);}
    private void CreateZip(string path,DmsReleaseHealthReport report){using var archive=ZipFile.Open(path,ZipArchiveMode.Create);Add(archive,"release-health.json",Json(report));Add(archive,"release-health.html",Html(report));Add(archive,"release-health.txt",Plain(report));var logPath=Path.Combine(_logsRoot,$"dms-{DateTime.Now:yyyy-MM-dd}.log");if(File.Exists(logPath)){var info=new FileInfo(logPath);const long max=2L*1024L*1024L;string text;if(info.Length<=max)text=File.ReadAllText(logPath);else{using var s=new FileStream(logPath,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);s.Seek(-max,SeekOrigin.End);using var r=new StreamReader(s);text="[Tail of current log; file exceeded 2 MB]\r\n"+r.ReadToEnd();}Add(archive,"logs/current-log.txt",text);}}
    private static void Add(ZipArchive a,string name,string text){var e=a.CreateEntry(name,CompressionLevel.Optimal);using var w=new StreamWriter(e.Open(),new UTF8Encoding(false));w.Write(text);}
    private static string Json(DmsReleaseHealthReport r)=>JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true});
    private static string Plain(DmsReleaseHealthReport r){var b=new StringBuilder();b.AppendLine("DMS RELEASE HEALTH");b.AppendLine($"Generated={r.GeneratedAt:yyyy-MM-dd HH:mm:ss}");b.AppendLine($"Verdict={r.Verdict}");b.AppendLine($"RQI={r.ReleaseQualityIndex:0.0}");b.AppendLine($"BuildAllowed={r.BuildAllowed}");b.AppendLine($"Environment={r.Environment}");b.AppendLine($"Version={r.Version}");b.AppendLine($"Critical={r.CriticalCount}; Errors={r.ErrorCount}; Warnings={r.WarningCount}; OK={r.OkCount}; Info={r.InfoCount}");b.AppendLine(new string('-',100));foreach(var x in r.Results)b.AppendLine($"{x.Severity}\t{x.FrameworkCode}\t{x.Category}\t{x.Name}\t{x.Details}\t{x.Source}\t{x.FixTransaction}");return b.ToString();}
    private static string Html(DmsReleaseHealthReport r){static string H(string? s)=>WebUtility.HtmlEncode(s??string.Empty);var b=new StringBuilder();b.AppendLine("<!doctype html><html><head><meta charset=\"utf-8\"><title>DMS Release Health</title><style>body{font-family:Segoe UI,Arial;margin:32px;color:#222}.cards{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.card{border:1px solid #bbb;border-radius:6px;padding:10px 14px;min-width:110px}.big{font-size:26px;font-weight:700}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #ccc;padding:7px;vertical-align:top;text-align:left}th{background:#eee}.CRITICAL,.ERROR{color:#a40000;font-weight:700}.WARNING{color:#8a5a00;font-weight:700}.OK{color:#176b20}</style></head><body>");b.AppendLine($"<h1>DMS Release Health</h1><div>{H(r.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss"))} | {H(r.Environment)} | v{H(r.Version)}</div><div class=\"cards\"><div class=\"card\"><div>Verdict</div><div class=\"big\">{H(r.Verdict)}</div></div><div class=\"card\"><div>RQI</div><div class=\"big\">{r.ReleaseQualityIndex:0.0}</div></div><div class=\"card\"><div>Critical</div><div class=\"big\">{r.CriticalCount}</div></div><div class=\"card\"><div>Errors</div><div class=\"big\">{r.ErrorCount}</div></div><div class=\"card\"><div>Warnings</div><div class=\"big\">{r.WarningCount}</div></div><div class=\"card\"><div>Passed</div><div class=\"big\">{r.OkCount}</div></div></div>");b.AppendLine("<table><thead><tr><th>Severity</th><th>Framework</th><th>Category</th><th>Check</th><th>Details</th><th>Source</th><th>Open</th></tr></thead><tbody>");foreach(var x in r.Results)b.AppendLine($"<tr><td class=\"{H(x.Severity)}\">{H(x.Severity)}</td><td>{H(x.FrameworkCode)}</td><td>{H(x.Category)}</td><td>{H(x.Name)}</td><td>{H(x.Details)}</td><td>{H(x.Source)}</td><td>{H(x.FixTransaction)}</td></tr>");b.AppendLine("</tbody></table></body></html>");return b.ToString();}
}
